version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - office-network
    environment:
      - BACKEND_URL=http://backend:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.frontend.backend
    ports:
      - "8080:8080"
    networks:
      - office-network

networks:
  office-network:
    driver: bridge